"ruby 2.1.6":
  script:
    - 'export RBENV_VERSION=2.1.6'
    - 'ruby -v'
    - 'bundle install --path vendor/bundle --without system_tests'
    - 'bundle exec rake lint validate spec SPEC_OPTS="--format documentation"'
    - bundle exec rake test

